BEGIN;

--------------------------------------------------------
-- ENUM TYPES
--------------------------------------------------------

CREATE TYPE client_type AS ENUM ('oneshot', 'mensuel');

CREATE TYPE client_status AS ENUM ('actif', 'pause', 'termine', 'potentiel');

CREATE TYPE mandat_status AS ENUM ('en_cours', 'termine', 'annule');

CREATE TYPE invoice_status AS ENUM ('brouillon', 'envoyee', 'payee', 'annulee');

CREATE TYPE expense_type AS ENUM ('client_mandat', 'yourstory');

CREATE TYPE recurrence_type AS ENUM ('oneshot', 'mensuel');

CREATE TYPE task_status AS ENUM ('a_faire', 'en_cours', 'terminee');

CREATE TYPE task_type AS ENUM ('contenu', 'video', 'reunion', 'reporting', 'autre');


--------------------------------------------------------
-- USER (login unique)
--------------------------------------------------------

CREATE TABLE public.app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.app_user (username, password_hash)
VALUES (
    'admin',
    '$2b$10$CHANGEMOI.EXEMPLE.DE.HASH.XXXXXXXXXXXXXXX'
);


--------------------------------------------------------
-- CLIENT
--------------------------------------------------------

CREATE TABLE public.client (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    type            client_type NOT NULL,
    status          client_status NOT NULL DEFAULT 'potentiel',
    email           TEXT,
    phone           TEXT,
    company_name    TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


--------------------------------------------------------
-- UPDATE TIMESTAMP FUNCTION
--------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_client_set_timestamp
BEFORE UPDATE ON public.client
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();


--------------------------------------------------------
-- MANDAT (projets clients)
--------------------------------------------------------

CREATE TABLE public.mandat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT,
    mandat_type     TEXT DEFAULT 'standard',
    status          mandat_status NOT NULL DEFAULT 'en_cours',
    start_date      DATE,
    end_date        DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_mandat_set_timestamp
BEFORE UPDATE ON public.mandat
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();


--------------------------------------------------------
-- TACHES DES MANDATS
--------------------------------------------------------

CREATE TABLE public.mandat_task (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandat_id       BIGINT NOT NULL REFERENCES public.mandat(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    details         TEXT,
    type            task_type NOT NULL DEFAULT 'autre',
    status          task_status NOT NULL DEFAULT 'a_faire',
    due_date        DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_mandat_task_set_timestamp
BEFORE UPDATE ON public.mandat_task
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();


--------------------------------------------------------
-- CONTRATS
--------------------------------------------------------

CREATE TABLE public.contrat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
    mandat_id       BIGINT REFERENCES public.mandat(id) ON DELETE SET NULL,
    contrat_number  TEXT NOT NULL UNIQUE,
    file_path       TEXT NOT NULL,
    signed_date     DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


--------------------------------------------------------
-- INVOICE (FACTURES)
--------------------------------------------------------

CREATE TABLE public.invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL REFERENCES public.client(id) ON DELETE CASCADE,
    mandat_id       BIGINT REFERENCES public.mandat(id) ON DELETE SET NULL,
    invoice_number  TEXT NOT NULL UNIQUE,
    issue_date      DATE NOT NULL,
    due_date        DATE,
    total_ht        NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_tva       NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_ttc       NUMERIC(10,2) NOT NULL DEFAULT 0,
    status          invoice_status NOT NULL DEFAULT 'brouillon',
    pdf_path        TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_invoice_set_timestamp
BEFORE UPDATE ON public.invoice
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();


--------------------------------------------------------
-- INVOICE ITEMS (lignes de facture)
--------------------------------------------------------

CREATE TABLE public.invoice_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT NOT NULL REFERENCES public.invoice(id) ON DELETE CASCADE,
    description     TEXT NOT NULL,
    quantity        NUMERIC(10,2) NOT NULL DEFAULT 1,
    unit_price      NUMERIC(10,2) NOT NULL DEFAULT 0,
    total           NUMERIC(10,2) NOT NULL DEFAULT 0
);


--------------------------------------------------------
-- EXPENSE CATEGORY
--------------------------------------------------------

CREATE TABLE public.expense_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    is_recurring    BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO public.expense_category (name, is_recurring) VALUES
('Logiciels', TRUE),
('Marketing & Publicité', FALSE),
('Déplacements', FALSE),
('Matériel', FALSE),
('Sous-traitance', FALSE),
('Abonnements', TRUE),
('Divers', FALSE);


--------------------------------------------------------
-- EXPENSES (dépenses)
--------------------------------------------------------

CREATE TABLE public.expense (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            expense_type NOT NULL,
    mandat_id       BIGINT REFERENCES public.mandat(id) ON DELETE SET NULL,
    client_id       BIGINT REFERENCES public.client(id) ON DELETE SET NULL,
    category_id     BIGINT REFERENCES public.expense_category(id) ON DELETE SET NULL,
    label           TEXT NOT NULL,
    amount          NUMERIC(10,2) NOT NULL,
    date            DATE NOT NULL,
    is_recurring    recurrence_type NOT NULL DEFAULT 'oneshot',
    notes           TEXT,
    receipt_path    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_expense_date ON public.expense(date);
CREATE INDEX idx_expense_type ON public.expense(type);


--------------------------------------------------------
-- COMPANY SETTINGS
--------------------------------------------------------

CREATE TABLE public.company_settings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_name     TEXT NOT NULL,
    address         TEXT,
    zip_code        TEXT,
    city            TEXT,
    country         TEXT,
    phone           TEXT,
    email           TEXT,
    tva_number      TEXT
);

INSERT INTO public.company_settings (
    agency_name, address, zip_code, city, country, phone, email, tva_number
)
VALUES (
    'YourStory Agency',
    'Rue Exemple 12',
    '2000',
    'Neuchâtel',
    'Suisse',
    '+41 79 000 00 00',
    'contact@urstory.ch',
    'CHE-000.000.000'
);


--------------------------------------------------------
-- AUDIT LOG
--------------------------------------------------------

CREATE TABLE public.audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    action          TEXT NOT NULL,
    details         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;

