-- Migration: Ajout de la table social_media_strategy
-- Date: 2025-12-02
-- Description: Permet de créer et gérer des stratégies social-media pour chaque mandat

BEGIN;

--------------------------------------------------------
-- TABLE: social_media_strategy
--------------------------------------------------------

CREATE TABLE public.social_media_strategy (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandat_id               BIGINT NOT NULL REFERENCES public.mandat(id) ON DELETE CASCADE,
    version                 INTEGER NOT NULL DEFAULT 1,
    status                  TEXT NOT NULL DEFAULT 'brouillon', -- brouillon, actif, archive
    
    -- 1. Contexte & objectifs business
    contexte_general        TEXT,
    objectifs_business      TEXT,
    objectifs_reseaux       TEXT,
    
    -- 2. Audience & Personas
    cibles                  TEXT,
    personas                JSONB, -- Array d'objets: [{nom, age, besoins, problemes, attentes}]
    plateformes             TEXT[], -- Array de plateformes: ['instagram', 'linkedin', etc.]
    
    -- 3. Positionnement & identité
    ton_voix                TEXT,
    guidelines_visuelles    TEXT,
    valeurs_messages        TEXT,
    
    -- 4. Piliers de contenu
    piliers_contenu         JSONB, -- Array d'objets: [{titre, description, exemples}]
    
    -- 5. Formats & rythme
    formats_envisages       TEXT[],
    frequence_calendrier    TEXT,
    workflow_roles          TEXT,
    
    -- 6. Audit & concurrence
    audit_profils           TEXT,
    benchmark_concurrents   TEXT,
    
    -- 7. KPIs & suivi
    kpis                    JSONB, -- Array d'objets: [{nom, objectif, periodicite}]
    cadre_suivi             TEXT,
    
    -- 8. Canaux & mix média (PESO)
    owned_media             TEXT,
    shared_media            TEXT,
    paid_media              TEXT,
    earned_media            TEXT,
    
    -- 9. Budget & ressources
    temps_humain            TEXT,
    outils                  TEXT,
    budget_pub              TEXT,
    
    -- 10. Planning & optimisation
    planning_global         TEXT,
    processus_iteration     TEXT,
    mise_a_jour             TEXT,
    
    -- Métadonnées
    notes_internes          TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by              TEXT,
    
    -- Contrainte: une seule stratégie "actif" par mandat
    CONSTRAINT unique_active_strategy_per_mandat 
        UNIQUE (mandat_id, status) 
        DEFERRABLE INITIALLY DEFERRED
);

-- Trigger pour updated_at
CREATE TRIGGER trg_social_media_strategy_set_timestamp
BEFORE UPDATE ON public.social_media_strategy
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();

-- Index pour requêtes fréquentes
CREATE INDEX idx_social_media_strategy_mandat_id ON public.social_media_strategy(mandat_id);
CREATE INDEX idx_social_media_strategy_status ON public.social_media_strategy(status);

-- Suppression de la contrainte unique si besoin (permet plusieurs versions actives)
ALTER TABLE public.social_media_strategy 
    DROP CONSTRAINT IF EXISTS unique_active_strategy_per_mandat;

COMMIT;
