--------------------------------------------------------
-- MIGRATION: Ajout des tables pour les tâches vidéo
-- Date: 2024-12-16
-- Description: Ajout des tables video_task_details et video_figurant
--              pour gérer les scripts vidéo et les figurants
--------------------------------------------------------

BEGIN;

-- Table pour les détails des tâches vidéo (script)
CREATE TABLE IF NOT EXISTS public.video_task_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         BIGINT NOT NULL REFERENCES public.mandat_task(id) ON DELETE CASCADE,
    script          TEXT,
    duration_minutes INTEGER,
    location        TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_task_video UNIQUE (task_id)
);

CREATE TRIGGER trg_video_task_details_set_timestamp
BEFORE UPDATE ON public.video_task_details
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();

-- Table pour les figurants des tâches vidéo
CREATE TABLE IF NOT EXISTS public.video_figurant (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_task_id   BIGINT NOT NULL REFERENCES public.video_task_details(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    contact         TEXT,
    role            TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_video_figurant_set_timestamp
BEFORE UPDATE ON public.video_figurant
FOR EACH ROW EXECUTE FUNCTION public.set_timestamp();

-- Index pour améliorer les performances
CREATE INDEX idx_video_task_details_task_id ON public.video_task_details(task_id);
CREATE INDEX idx_video_figurant_video_task_id ON public.video_figurant(video_task_id);

COMMIT;
